python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/fedsa-lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/fedsa-rslora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/fedsa-vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/ffa-lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/ffa-rslora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/ffa-vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/sst2/rslora.yaml