python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/fedsa-lora.yaml
python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/fedsa-rslora.yaml
python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/fedsa-vera.yaml
python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/ffa-lora.yaml
python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/ffa-rslora.yaml
python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/ffa-vera.yaml
python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/lora.yaml
python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/vera.yaml
python3 federatedscope/main.py --cfg federatedscope/glue/yamls/qqp/rslora.yaml