python federatedscope/main.py --cfg federatedscope/glue/yamls/mnli/vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/fedsa-lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/fedsa-rslora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/fedsa-vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/ffa-lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/ffa-rslora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/ffa-vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/rte/rslora.yaml