python federatedscope/main.py --cfg federatedscope/glue/yamls/mnli/rslora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/fedsa-lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/fedsa-rslora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/fedsa-vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/ffa-lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/ffa-rslora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/ffa-vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/lora.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/vera.yaml
python federatedscope/main.py --cfg federatedscope/glue/yamls/qnli/rslora.yaml